INSERT INTO roles (id, slug, name) VALUES
(1, 'super-admin', 'Super Admin'),
(2, 'content-manager', 'Content Manager'),
(3, 'editor', 'Editor');

INSERT INTO permissions (slug, name) VALUES
('manage_pages', 'Manage Pages'),
('manage_services', 'Manage Services'),
('manage_posts', 'Manage Posts'),
('manage_banners', 'Manage Banners'),
('manage_settings', 'Manage Settings'),
('manage_media', 'Manage Media'),
('view_contacts', 'View Contacts'),
('view_newsletters', 'View Newsletter Subscribers'),
('manage_logs', 'Manage Operation Logs'),
('manage_admins', 'Manage Admins');

INSERT INTO role_permissions (role_id, permission_id)
SELECT 2, id FROM permissions WHERE slug IN ('manage_pages', 'manage_services', 'manage_posts', 'manage_banners', 'manage_settings', 'manage_media', 'view_contacts', 'view_newsletters');

INSERT INTO role_permissions (role_id, permission_id)
SELECT 3, id FROM permissions WHERE slug IN ('manage_pages', 'manage_services', 'manage_posts', 'manage_banners', 'manage_media');

INSERT INTO admins (role_id, username, password_hash, name, email, is_active, created_at, updated_at) VALUES
(1, 'admin', 'plain:admin123456', 'Planet Admin', 'admin@planetaviation.com', 1, NOW(), NOW());

INSERT INTO pages (slug, template, status, sort_order, seo_image, created_at, updated_at) VALUES
('about', 'about', 'published', 1, 'assets/figma/about-photo.png', NOW(), NOW()),
('contact', 'contact', 'published', 2, 'assets/figma/contact-photo.png', NOW(), NOW());

INSERT INTO page_translations (page_id, locale, title, excerpt, content, seo_title, seo_keywords, seo_description) VALUES
(1, 'en', 'About Us', 'PLANET AVIATION, S.L. is a globally recognized General Sales & Service Agent headquartered in Europe.', '<p>PLANET AVIATION, S.L. is a globally recognized General Sales & Service Agent (GSSA) headquartered in Europe, dedicated to bridging the gap between complex logistics needs and streamlined execution. We pride ourselves on delivering tailor-made, highly specialized solutions that empower our customers to navigate the ever-evolving aviation landscape with confidence.</p><p>We are redefining GSSA expertise through a four-pillar strategy: Commercialization, Technology, Solutions, and Sustainability. By leveraging our extensive local market knowledge, we enable freight forwarders to maximize their operational performance and achieve superior commercial results.</p><p>Recognizing that air service is the backbone of global supply chain security, we go beyond standard logistics. Planet Aviation offers comprehensive cargo insurance packages designed to provide robust risk prevention and loss compensation.</p>', 'About Planet Aviation', 'aviation, gssa, logistics', 'Learn more about Planet Aviation.'),
(1, 'es', 'About Us', 'PLANET AVIATION, S.L. is a globally recognized General Sales & Service Agent headquartered in Europe.', '<p>PLANET AVIATION, S.L. is a globally recognized General Sales & Service Agent (GSSA) headquartered in Europe, dedicated to bridging the gap between complex logistics needs and streamlined execution.</p>', 'About Planet Aviation', 'aviation, gssa, logistics', 'Learn more about Planet Aviation.'),
(2, 'en', 'Contact Us', 'If you need further information about our services, please fill out the form below. Our team of logistics experts will get in touch with you as soon as possible.', '<p>Share your schedule, routing, or document needs and our operations team will reply quickly.</p>', 'Contact Planet Aviation', 'contact, aviation', 'Reach the Planet Aviation team.'),
(2, 'es', 'Contact Us', 'If you need further information about our services, please fill out the form below. Our team of logistics experts will get in touch with you as soon as possible.', '<p>Share your schedule, routing, or document needs and our operations team will reply quickly.</p>', 'Contact Planet Aviation', 'contact, aviation', 'Reach the Planet Aviation team.');

INSERT INTO services (slug, icon, cover_image, status, sort_order, created_at, updated_at) VALUES
('general-sales-service-agent', 'GS', 'assets/figma/service_2.png', 'published', 1, NOW(), NOW()),
('air-cargo-consolidation-experts', 'AC', 'assets/figma/service_2.png', 'published', 2, NOW(), NOW()),
('handling-trucking', 'HT', 'assets/figma/service_4.png', 'published', 3, NOW(), NOW()),
('insurance-solutions', 'IS', 'assets/figma/service_4.png', 'published', 4, NOW(), NOW());

INSERT INTO service_translations (service_id, locale, title, summary, content, seo_title, seo_keywords, seo_description) VALUES
(1, 'en', 'General Sales & Service Agent', 'Specializing in air freight operations across Europe, Asia, Middle East and Latin America.', '<ul><li>Delivered 1,200,000+ tons of cargo worldwide</li><li>Dynamic capacity allocation for maximum yield optimization</li><li>Consistent achievement and surpassing of airline sales targets</li></ul>', 'General Sales & Service Agent', 'gssa, cargo sales', 'Full GSSA representation for airline principals.'),
(1, 'es', 'General Sales & Service Agent', 'Specializing in air freight operations across Europe, Asia, Middle East and Latin America.', '<ul><li>Delivered 1,200,000+ tons of cargo worldwide</li><li>Dynamic capacity allocation for maximum yield optimization</li><li>Consistent achievement and surpassing of airline sales targets</li></ul>', 'General Sales & Service Agent', 'gssa, cargo sales', 'Full GSSA representation for airline principals.'),
(2, 'en', 'Air Cargo Consolidation Experts', 'Strategic capacity optimization and rapid consolidation solutions.', '<ul><li>Strategic Capacity Optimization: maximizing cubic yield</li><li>Precise Capacity Management: effective route utilization</li><li>Dynamic Payload Adjustments: real-time flexibility</li><li>Rapid Air Consolidation Solutions: fast turnaround groupings</li></ul>', 'Air Cargo Consolidation Experts', 'air cargo, consolidation', 'Cargo consolidation and capacity management.'),
(2, 'es', 'Air Cargo Consolidation Experts', 'Strategic capacity optimization and rapid consolidation solutions.', '<ul><li>Strategic Capacity Optimization: maximizing cubic yield</li><li>Precise Capacity Management: effective route utilization</li><li>Dynamic Payload Adjustments: real-time flexibility</li><li>Rapid Air Consolidation Solutions: fast turnaround groupings</li></ul>', 'Air Cargo Consolidation Experts', 'air cargo, consolidation', 'Cargo consolidation and capacity management.'),
(3, 'en', 'Handling & Trucking', 'Strong ground handling with superior service and cost-effective trucking.', '<ul><li>Strong ground handling with superior service</li><li>Cost-effective handling and trucking solutions</li><li>Import handling and administration services</li></ul>', 'Handling & Trucking', 'handling, trucking', 'Ground handling and trucking services.'),
(3, 'es', 'Handling & Trucking', 'Strong ground handling with superior service and cost-effective trucking.', '<ul><li>Strong ground handling with superior service</li><li>Cost-effective handling and trucking solutions</li><li>Import handling and administration services</li></ul>', 'Handling & Trucking', 'handling, trucking', 'Ground handling and trucking services.'),
(4, 'en', 'Insurance Solutions', 'Comprehensive cargo insurance solutions for airline and logistics partners.', '<ul><li>Comprehensive Global Coverage</li><li>Flexible Policy Options for all shipment types</li><li>Fast Track Claims Processing</li></ul>', 'Insurance Solutions', 'insurance, cargo insurance', 'Cargo insurance products for logistics partners.'),
(4, 'es', 'Insurance Solutions', 'Comprehensive cargo insurance solutions for airline and logistics partners.', '<ul><li>Comprehensive Global Coverage</li><li>Flexible Policy Options for all shipment types</li><li>Fast Track Claims Processing</li></ul>', 'Insurance Solutions', 'insurance, cargo insurance', 'Cargo insurance products for logistics partners.');

INSERT INTO post_categories (type, name, sort_order) VALUES
('news', 'Insights', 1),
('document', 'Documents', 1);

INSERT INTO posts (type, category_id, slug, cover_image, attachment_path, attachment_name, status, is_pinned, is_featured, sort_order, published_at, created_at, updated_at) VALUES
('news', 1, 'planet-aviation-expands-regional-network', 'assets/figma/news-1.png', NULL, NULL, 'published', 1, 1, 1, NOW(), NOW(), NOW()),
('news', 1, 'air-cargo-market-analysis', 'assets/figma/news-2.png', NULL, NULL, 'published', 0, 1, 2, NOW(), NOW(), NOW()),
('news', 1, 'transport-logistic-air-cargo-europe', 'assets/figma/news-3.png', NULL, NULL, 'published', 0, 0, 3, NOW(), NOW(), NOW()),
('document', 2, 'new-documentation-checklist-for-summer-operations', 'assets/figma/news-2.png', NULL, NULL, 'published', 1, 0, 1, NOW(), NOW(), NOW());

INSERT INTO post_translations (post_id, locale, title, excerpt, content, seo_title, seo_keywords, seo_description) VALUES
(1, 'en', 'Planet Aviation expands regional network support', 'A new operating framework improves coordination speed for partner operators.', '<p>Planet Aviation has expanded its regional operating network to streamline support requests and improve partner visibility across active missions.</p>', 'Planet Aviation News', 'aviation news', 'Regional network support update.'),
(1, 'es', 'Planet Aviation expands regional network support', 'A new operating framework improves coordination speed for partner operators.', '<p>Planet Aviation has expanded its regional operating network to streamline support requests and improve partner visibility across active missions.</p>', 'Planet Aviation News', 'aviation news', 'Regional network support update.'),
(2, 'en', 'Air Cargo Market Analysis 2026: The Shift', 'A fresh market analysis highlights the lane shifts shaping current cargo demand.', '<p>New market data shows sharper demand movement across regional cargo corridors, pushing operators toward more dynamic consolidation and pricing strategies.</p>', 'Air Cargo Market Analysis', 'market analysis, cargo', 'Air cargo market analysis.'),
(2, 'es', 'Air Cargo Market Analysis 2026: The Shift', 'A fresh market analysis highlights the lane shifts shaping current cargo demand.', '<p>New market data shows sharper demand movement across regional cargo corridors, pushing operators toward more dynamic consolidation and pricing strategies.</p>', 'Air Cargo Market Analysis', 'market analysis, cargo', 'Air cargo market analysis.'),
(3, 'en', 'Transport Logistic & Air Cargo Europe 2025', 'Highlights from one of the leading logistics and air cargo trade events.', '<p>Planet Aviation reviews the operating trends, carrier strategies, and partner conversations emerging from this year''s major air cargo event.</p>', 'Transport Logistic Europe', 'transport logistic, air cargo', 'Event highlights from Europe.'),
(3, 'es', 'Transport Logistic & Air Cargo Europe 2025', 'Highlights from one of the leading logistics and air cargo trade events.', '<p>Planet Aviation reviews the operating trends, carrier strategies, and partner conversations emerging from this year''s major air cargo event.</p>', 'Transport Logistic Europe', 'transport logistic, air cargo', 'Event highlights from Europe.'),
(4, 'en', 'New documentation checklist for summer operations', 'A standard document pack is now recommended for charter support requests.', '<p>The operations team recommends a standard documentation checklist covering permits, handler coordination, passenger manifests, and airport slots for summer operations.</p>', 'Operations Checklist', 'operations checklist', 'Document checklist update.'),
(4, 'es', 'New documentation checklist for summer operations', 'A standard document pack is now recommended for charter support requests.', '<p>The operations team recommends a standard documentation checklist covering permits, handler coordination, passenger manifests, and airport slots for summer operations.</p>', 'Operations Checklist', 'operations checklist', 'Document checklist update.');

INSERT INTO banners (image, link, status, sort_order, created_at, updated_at) VALUES
('assets/figma/hero-plane.png', '/about', 'published', 1, NOW(), NOW());

INSERT INTO banner_translations (banner_id, locale, title, subtitle, button_text) VALUES
(1, 'en', 'Premium Choice For Air Logistics Solution!', 'Specializing in air freight operations across Europe, Asia, Middle East and Latin America.', 'LEARN MORE'),
(1, 'es', 'Premium Choice For Air Logistics Solution!', 'Specializing in air freight operations across Europe, Asia, Middle East and Latin America.', 'LEARN MORE');

INSERT INTO site_settings (locale, setting_key, setting_value, updated_at) VALUES
('en', 'site_name', 'PLANET AVIATION', NOW()),
('en', 'site_meta_title', 'Planet Aviation', NOW()),
('en', 'site_meta_keywords', 'aviation, air cargo, logistics, GSSA', NOW()),
('en', 'site_meta_description', 'Planet Aviation provides air cargo, GSSA, logistics, handling, trucking, and insurance solutions.', NOW()),
('en', 'site_og_image', 'assets/figma/hero-plane.png', NOW()),
('en', 'homepage_meta_title', 'Premium Choice For Air Logistics Solution!', NOW()),
('en', 'homepage_meta_keywords', 'air logistics, air cargo, GSSA, freight forwarding', NOW()),
('en', 'homepage_meta_description', 'Specializing in air freight operations across Europe, Asia, Middle East and Latin America.', NOW()),
('en', 'homepage_og_image', 'assets/figma/hero-plane.png', NOW()),
('en', 'hero_kicker', 'PLANET AVIATION, S.L.,', NOW()),
('en', 'nav_home_label', 'Home', NOW()),
('en', 'nav_about_label', 'Who We Are?', NOW()),
('en', 'nav_services_label', 'Our Services', NOW()),
('en', 'nav_insights_label', 'Insights', NOW()),
('en', 'nav_documents_label', 'Documents', NOW()),
('en', 'nav_contact_label', 'Contact', NOW()),
('en', 'nav_quote_label', 'GET A QUOTE', NOW()),
('en', 'homepage_title', 'Premium Choice\nFor Air Logistics Solution!', NOW()),
('en', 'homepage_subtitle', 'Specializing in air freight operations across Europe, Asia, Middle East and Latin America, we act as a strategic extension of airline principals.', NOW()),
('en', 'hero_button_text', 'LEARN MORE', NOW()),
('en', 'lookup_label', 'I''m looking for', NOW()),
('en', 'lookup_insurance_label', 'Insurance', NOW()),
('en', 'home_about_heading', 'Your Leading Air Cargo Sales & Service Provider', NOW()),
('en', 'home_about_body', 'PLANET AVIATION, S.L. is a globally recognized General Sales & Service Agent (GSSA) headquartered in Europe. We bridge the gap between complex logistics needs and streamlined execution, with a service model built on commercialization, technology, solutions, and sustainability.', NOW()),
('en', 'home_about_button', 'LEARN MORE', NOW()),
('en', 'services_kicker_label', 'View all', NOW()),
('en', 'services_filter_label', 'Products & Services', NOW()),
('en', 'services_heading', 'Delivering Service Excellence', NOW()),
('en', 'services_intro', 'Planet Aviation offers a comprehensive portfolio of air cargo products and services. Every shipment is handled with precision, care, and professionalism, ensuring reliability at every stage of the logistics chain.', NOW()),
('en', 'services_fourth_home_title', 'General Sales & Service Agent', NOW()),
('en', 'services_learn_more_label', 'LEARN MORE', NOW()),
('en', 'why_heading', 'Why Partners Choose Us', NOW()),
('en', 'why_background_image', 'assets/figma/why-bg.png', NOW()),
('en', 'world_kicker_label', 'GLOBAL MANAGEMENT. LOCAL EXPERTISE.', NOW()),
('en', 'why_items', 'Independent GSSA\nStrong Financial Background\nDigital Marketing\nMotivated & Experienced Teams\nBusiness Intelligence\nFull Service - Sales to Invoicing', NOW()),
('en', 'world_heading', 'One World', NOW()),
('en', 'world_intro', 'Global management with local expertise across the Americas, Europe, the Middle East, Africa, and Asia Pacific.', NOW()),
('en', 'world_regions', 'Americas\nEurope\nMiddle East\nAfrica\nAsia Pacific', NOW()),
('en', 'world_map_image', 'assets/figma/world-map.png', NOW()),
('en', 'stats_offices', '100+', NOW()),
('en', 'stats_offices_label', 'Global Partners', NOW()),
('en', 'stats_support', '24/7', NOW()),
('en', 'stats_support_label', 'Rapid Response Team', NOW()),
('en', 'stats_shipments', '16,000+', NOW()),
('en', 'stats_shipments_label', 'Freight Forwarders', NOW()),
('en', 'partners_heading', 'Our Partners', NOW()),
('en', 'partners_subtitle', 'These are our collaborators', NOW()),
('en', 'partners_list', 'OOCL\nDHL\nMSC\nMNG\nHainan Airlines\nIAC', NOW()),
('en', 'partners_logos', 'MNG Airlines|assets/figma/partner-1.png\nHainan Airlines|assets/figma/partner-2.png\nCapital Airlines|assets/figma/partner-3.png\nChina Southern|assets/figma/partner-4.png\nBAC|assets/figma/partner-5.png', NOW()),
('en', 'news_kicker_label', 'INSIGHT', NOW()),
('en', 'news_heading', 'Latest News', NOW()),
('en', 'news_view_all_label', 'VIEW ALL ARTICLES', NOW()),
('en', 'read_more_label', 'READ MORE', NOW()),
('en', 'download_attachment_label', 'DOWNLOAD ATTACHMENT', NOW()),
('en', 'contact_heading', 'Contact Us', NOW()),
('en', 'contact_intro', 'If you need further information about our services, please fill out the form below. Our team of logistics experts will get in touch with you as soon as possible.', NOW()),
('en', 'contact_visual_image', 'assets/figma/contact-photo.png', NOW()),
('en', 'contact_name_label', 'Full Name', NOW()),
('en', 'contact_phone_label', 'Phone', NOW()),
('en', 'contact_email_label', 'Email Address', NOW()),
('en', 'contact_company_label', 'Company', NOW()),
('en', 'contact_message_label', 'Message', NOW()),
('en', 'contact_submit_text', 'SUBMIT', NOW()),
('en', 'newsletter_title', 'Sign Up To The Logistics Pulse Newsletter', NOW()),
('en', 'newsletter_body', 'Receive our insights directly in your mailbox by signing up through this form and enter a world of truly integrated logistics. Get inspired by our selection of articles that help you navigate supply chains, understand industry trends, and shape your logistics strategy.', NOW()),
('en', 'newsletter_placeholder', 'Enter your email address', NOW()),
('en', 'newsletter_submit_text', 'SUBMIT', NOW()),
('en', 'newsletter_background_image', 'assets/figma/newsletter-bg.png', NOW()),
('en', 'contact_email', 'ops@planetaviation.com', NOW()),
('en', 'contact_phone', '+34 000 000 000', NOW()),
('en', 'office_address', 'Madrid, Spain', NOW()),
('en', 'footer_pages_title', 'Pages', NOW()),
('en', 'footer_services_title', 'Services', NOW()),
('en', 'footer_about_title', 'About', NOW()),
('en', 'footer_home_label', 'Home', NOW()),
('en', 'footer_events_label', 'Events', NOW()),
('en', 'footer_awards_label', 'Our awards', NOW()),
('en', 'footer_contact_label', 'Contact', NOW()),
('en', 'footer_news_label', 'News', NOW()),
('en', 'footer_certification_label', 'Obtain IATA certification', NOW()),
('en', 'footer_copyright', 'Copyright (c) Planet Aviation. All Rights Reserved', NOW()),
('en', 'page_not_found_message', 'The requested page is not available.', NOW()),
('en', 'service_not_found_message', 'The requested service is not available.', NOW()),
('en', 'post_not_found_message', 'The requested content is not available.', NOW()),
('en', 'contact_error_invalid', 'Your session expired. Please try again.', NOW()),
('en', 'contact_error_required', 'Name, email, and message are required.', NOW()),
('en', 'contact_success_message', 'Your request has been sent.', NOW()),
('en', 'newsletter_error_required', 'Please enter a valid email address.', NOW()),
('en', 'newsletter_error_duplicate', 'This email address is already subscribed.', NOW()),
('en', 'newsletter_success_message', 'Thank you for subscribing to our newsletter.', NOW()),
('es', 'site_name', 'PLANET AVIATION', NOW()),
('es', 'site_meta_title', 'Planet Aviation', NOW()),
('es', 'site_meta_keywords', 'aviacion, carga aerea, logistica, GSSA', NOW()),
('es', 'site_meta_description', 'Planet Aviation ofrece soluciones de carga aerea, GSSA, logistica, handling, transporte terrestre y seguros.', NOW()),
('es', 'site_og_image', 'assets/figma/hero-plane.png', NOW()),
('es', 'homepage_meta_title', 'Soluciones premium para logistica aerea', NOW()),
('es', 'homepage_meta_keywords', 'logistica aerea, carga aerea, GSSA, transitarios', NOW()),
('es', 'homepage_meta_description', 'Especialistas en operaciones de carga aerea en Europa, Asia, Oriente Medio y America Latina.', NOW()),
('es', 'homepage_og_image', 'assets/figma/hero-plane.png', NOW()),
('es', 'hero_kicker', 'PLANET AVIATION, S.L.,', NOW()),
('es', 'nav_home_label', 'Home', NOW()),
('es', 'nav_about_label', 'Who We Are?', NOW()),
('es', 'nav_services_label', 'Our Services', NOW()),
('es', 'nav_insights_label', 'Insights', NOW()),
('es', 'nav_documents_label', 'Documents', NOW()),
('es', 'nav_contact_label', 'Contact', NOW()),
('es', 'nav_quote_label', 'GET A QUOTE', NOW()),
('es', 'homepage_title', 'Premium Choice\nFor Air Logistics Solution!', NOW()),
('es', 'homepage_subtitle', 'Specializing in air freight operations across Europe, Asia, Middle East and Latin America.', NOW()),
('es', 'hero_button_text', 'LEARN MORE', NOW()),
('es', 'lookup_label', 'I''m looking for', NOW()),
('es', 'lookup_insurance_label', 'Insurance', NOW()),
('es', 'home_about_heading', 'Your Leading Air Cargo Sales & Service Provider', NOW()),
('es', 'home_about_body', 'PLANET AVIATION, S.L. is a globally recognized General Sales & Service Agent (GSSA) headquartered in Europe.', NOW()),
('es', 'home_about_button', 'LEARN MORE', NOW()),
('es', 'services_kicker_label', 'View all', NOW()),
('es', 'services_filter_label', 'Products & Services', NOW()),
('es', 'services_heading', 'Delivering Service Excellence', NOW()),
('es', 'services_intro', 'Planet Aviation offers a comprehensive portfolio of air cargo products and services.', NOW()),
('es', 'services_fourth_home_title', 'General Sales & Service Agent', NOW()),
('es', 'services_learn_more_label', 'LEARN MORE', NOW()),
('es', 'why_heading', 'Why Partners Choose Us', NOW()),
('es', 'why_background_image', 'assets/figma/why-bg.png', NOW()),
('es', 'world_kicker_label', 'GLOBAL MANAGEMENT. LOCAL EXPERTISE.', NOW()),
('es', 'why_items', 'Independent GSSA\nStrong Financial Background\nDigital Marketing\nMotivated & Experienced Teams\nBusiness Intelligence\nFull Service - Sales to Invoicing', NOW()),
('es', 'world_heading', 'One World', NOW()),
('es', 'world_intro', 'Global management with local expertise across the Americas, Europe, the Middle East, Africa, and Asia Pacific.', NOW()),
('es', 'world_regions', 'Americas\nEurope\nMiddle East\nAfrica\nAsia Pacific', NOW()),
('es', 'world_map_image', 'assets/figma/world-map.png', NOW()),
('es', 'stats_offices', '100+', NOW()),
('es', 'stats_offices_label', 'Global Partners', NOW()),
('es', 'stats_support', '24/7', NOW()),
('es', 'stats_support_label', 'Rapid Response Team', NOW()),
('es', 'stats_shipments', '16,000+', NOW()),
('es', 'stats_shipments_label', 'Freight Forwarders', NOW()),
('es', 'partners_heading', 'Our Partners', NOW()),
('es', 'partners_subtitle', 'These are our collaborators', NOW()),
('es', 'partners_list', 'OOCL\nDHL\nMSC\nMNG\nHainan Airlines\nIAC', NOW()),
('es', 'partners_logos', 'MNG Airlines|assets/figma/partner-1.png\nHainan Airlines|assets/figma/partner-2.png\nCapital Airlines|assets/figma/partner-3.png\nChina Southern|assets/figma/partner-4.png\nBAC|assets/figma/partner-5.png', NOW()),
('es', 'news_kicker_label', 'INSIGHT', NOW()),
('es', 'news_heading', 'Latest News', NOW()),
('es', 'news_view_all_label', 'VIEW ALL ARTICLES', NOW()),
('es', 'read_more_label', 'READ MORE', NOW()),
('es', 'download_attachment_label', 'DOWNLOAD ATTACHMENT', NOW()),
('es', 'contact_heading', 'Contact Us', NOW()),
('es', 'contact_intro', 'If you need further information about our services, please fill out the form below. Our team of logistics experts will get in touch with you as soon as possible.', NOW()),
('es', 'contact_visual_image', 'assets/figma/contact-photo.png', NOW()),
('es', 'contact_name_label', 'Full Name', NOW()),
('es', 'contact_phone_label', 'Phone', NOW()),
('es', 'contact_email_label', 'Email Address', NOW()),
('es', 'contact_company_label', 'Company', NOW()),
('es', 'contact_message_label', 'Message', NOW()),
('es', 'contact_submit_text', 'SUBMIT', NOW()),
('es', 'newsletter_title', 'Sign Up To The Logistics Pulse Newsletter', NOW()),
('es', 'newsletter_body', 'Receive our insights directly in your mailbox by signing up through this form and enter a world of truly integrated logistics.', NOW()),
('es', 'newsletter_placeholder', 'Enter your email address', NOW()),
('es', 'newsletter_submit_text', 'SUBMIT', NOW()),
('es', 'newsletter_background_image', 'assets/figma/newsletter-bg.png', NOW()),
('es', 'contact_email', 'ops@planetaviation.com', NOW()),
('es', 'contact_phone', '+34 000 000 000', NOW()),
('es', 'office_address', 'Madrid, Spain', NOW()),
('es', 'footer_pages_title', 'Pages', NOW()),
('es', 'footer_services_title', 'Services', NOW()),
('es', 'footer_about_title', 'About', NOW()),
('es', 'footer_home_label', 'Home', NOW()),
('es', 'footer_events_label', 'Events', NOW()),
('es', 'footer_awards_label', 'Our awards', NOW()),
('es', 'footer_contact_label', 'Contact', NOW()),
('es', 'footer_news_label', 'News', NOW()),
('es', 'footer_certification_label', 'Obtain IATA certification', NOW()),
('es', 'footer_copyright', 'Copyright (c) Planet Aviation. All Rights Reserved', NOW()),
('es', 'page_not_found_message', 'The requested page is not available.', NOW()),
('es', 'service_not_found_message', 'The requested service is not available.', NOW()),
('es', 'post_not_found_message', 'The requested content is not available.', NOW()),
('es', 'contact_error_invalid', 'Your session expired. Please try again.', NOW()),
('es', 'contact_error_required', 'Name, email, and message are required.', NOW()),
('es', 'contact_success_message', 'Your request has been sent.', NOW()),
('es', 'newsletter_error_required', 'Please enter a valid email address.', NOW()),
('es', 'newsletter_error_duplicate', 'This email address is already subscribed.', NOW()),
('es', 'newsletter_success_message', 'Thank you for subscribing to our newsletter.', NOW());
