-- Deprecated legacy patch.
-- Do not import this file for the current bilingual Planet Aviation build.
--
-- Current database update order:
-- 1. database/patches/2026_06_14_cms_operations.sql
-- 2. database/patches/2026_06_14_spanish_frontend.sql
--
-- The old 2026-06-12 patch was replaced because the site now uses English and
-- Spanish only. Chinese frontend/CMS content rows are intentionally removed.
